#ifndef _VALVE_REGISTERS_H_
#define _VALVE_REGISTERS_H_

#define MAX_ADDRESS									5

/* Start Address */
#define ADDRESS_START_CFG_MEMORY		0x10067000

/* Flag setted after first configuration */
#define	ADDRESS_CONFIGURED 					ADDRESS_START_CFG_MEMORY
#define CONFIG_SIZE									10
#define STEP_SIZE										1
#define ZONE_SIZE										1
#define	NAME_SIZE										12

/* START ADDRESS FOR CONFIGURATION DATA AREA */
#define ADDRESS_INITIAL_NAME				ADDRESS_CONFIGURED + CONFIG_SIZE
#define ADDRESS_START_STEPS					ADDRESS_INITIAL_NAME+NAME_SIZE
#define ADDRESS_STOP_STEPS					ADDRESS_START_STEPS+STEP_SIZE
#define ADDRESS_ZONE								ADDRESS_STOP_STEPS+STEP_SIZE

#define TIME_SIZE				6
#define	FLAG_TEMP_SIZE	1

/* 3 bytes - HH:MM:SS */
#define DATE_SIZE						3
#define	TEMP_VAL_SIZE				1
#define N_MAX_CONF_PER_DAY	4

/* N_MAX_CONF * START_TIME|END_TIME|TEMP_DESIDERED */
#define DAY_CONF_SIZE								N_MAX_CONF_PER_DAY*(2*DATE_SIZE+TEMP_VAL_SIZE)

#define MACs_SIZE										MAX_ADDRESS*6
#define MAX_ROLE_SIZE								20

#define ADDRESS_TIME 								ADDRESS_ZONE + ZONE_SIZE
#define ADDRESS_FIXED_TEMP_FLAG			ADDRESS_TIME + TIME_SIZE
#define ADDRESS_MONDAY							ADDRESS_FIXED_TEMP_FLAG + FLAG_TEMP_SIZE
#define	ADDRESS_TUESDAY							ADDRESS_MONDAY + DAY_CONF_SIZE
#define	ADDRESS_WEDNESDAY						ADDRESS_TUESDAY + DAY_CONF_SIZE
#define	ADDRESS_THURSDAY						ADDRESS_WEDNESDAY + DAY_CONF_SIZE
#define	ADDRESS_FRIDAY							ADDRESS_THURSDAY + DAY_CONF_SIZE
#define	ADDRESS_SATURDAY						ADDRESS_FRIDAY + DAY_CONF_SIZE
#define	ADDRESS_SUNDAY							ADDRESS_SATURDAY + DAY_CONF_SIZE
#define	ADDRESS_FIXED_TEMP_VAL			ADDRESS_SUNDAY + DAY_CONF_SIZE
#define	ADDRESS_TRUSTED_MACs				ADDRESS_FIXED_TEMP_VAL + TEMP_VAL_SIZE
#define ADDRESS_ROLE								ADDRESS_TRUSTED_MACs +	MACs_SIZE

#define MEMORY_SIZE									MAX_ROLE_SIZE +(ADDRESS_ROLE - ADDRESS_CONFIGURED)
#endif	
